version: '3'
services:
  web:
    build: "Dockerfile"
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
  mongo:
    image: "redis:alpine"
